### ISSUE TITLE
#297 NSInvalidUnarchiveOperationException: *** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (VungleInternalMRAIDAd) for key (root); the class may be defined in source code or a library that is not linked 

### ISSUE THREAD

**Issue by charlesbodman** [appodeal/appodeal-cordova-nodex-plugin#1]
We currently have a very popular app that is seeing errors come through using appodeal. 

#297 NSInvalidUnarchiveOperationException: *** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (VungleInternalMRAIDAd) for key (root); the class may be defined in source code or a library that is not linked 

This causes our app to crash.

**Comment by MittaKarthik** [comment]
I am getting same issue when I create a duplicate target for my original target and run. Can you please tell me, what is the solution you have applied and reason for that.
