### ISSUE TITLE
Cordova2 contains wrong Appodeal framework code.

### ISSUE THREAD

**Issue by charlesbodman** [appodeal/appodeal-cordova-nodex-plugin#3]
I noticed you guys updated the cordova2 branch , but I noticed it doesn't contain 2.0 appodeal framework code. 

`Appodeal does not contain canShowAd `

**Comment by Tamplier** [comment]
@charlesbodman, sorry for the inconvenience. Method is called canShow. Here is a small example: 
```
Appodeal.canShow(Appodeal.INTERSTITIAL, "default", function(result){
			console.log("Appodeal. " + result);
		});
```
I just checked - all work fine.

**Comment by charlesbodman** [comment]
@templier

Thanks for the response, but I think you misunderstood me. 

Cordova 2 branch contains the old iOS Appodeal framework . It does not contain 2.0 framework. 

**(WRONG) Cordova Appodeal 2.0 No Dex Plugin**
https://github.com/appodeal/appodeal-cordova-nodex-plugin/blob/cordova2/libs/iOS/Appodeal/Appodeal.framework/Headers/Appodeal.h


**Cordova Appodeal 2.0 Plugin ( With multidex )**
https://github.com/appodeal/appodeal-cordova-plugin/blob/cordova2/libs/iOS/Appodeal/Appodeal.framework/Headers/Appodeal.h


Let me know if I need to clarify

**Comment by Tamplier** [comment]
@charlesbodman, oh... 
Sorry for such long delay. You can find a version with new iOS SDK here:
https://github.com/appodeal/appodeal-cordova-nodex-plugin/tree/cordova2_ios_fix

Please notify me if it'll fix the problem (or if it won't).
